name: dados_anvisa
on: 
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * *'
  
jobs:
  busca_dados:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2

      - name: Install packages
        run: |
          install.packages("dplyr")
          install.packages("httr2")
          install.packages("lubridate")
          install.packages("glue")
        shell: Rscript {0}
        
      - name: Get data and upload file
        run: Rscript get_data.R
        
      - name: Commit results
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
